### ISSUE TITLE
CLI flags broken in released version

### ISSUE THREAD

**Issue by afeld** [markdownlint/markdownlint#123]
Cool project! I was trying to use the tool, but it seems that using the `--tags` and `--rules` CLI flags are throwing exceptions:

```
$ gem install mdl
Fetching: mdl-0.2.1.gem (100%)
Successfully installed mdl-0.2.1
1 gem installed
$ mdl --tags ~line_length README.md
/Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/mdl-0.2.1/lib/mdl/cli.rb:102:in `block in toggle_list': undefined method `start_with?' for :include:Symbol (NoMethodError)
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/mdl-0.2.1/lib/mdl/cli.rb:102:in `select'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/mdl-0.2.1/lib/mdl/cli.rb:102:in `toggle_list'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/mdl-0.2.1/lib/mdl/cli.rb:88:in `run'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/mdl-0.2.1/lib/mdl.rb:14:in `run'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/gems/mdl-0.2.1/bin/mdl:10:in `<top (required)>'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/mdl:23:in `load'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/mdl:23:in `<main>'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/aidanfeldman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Thankfully, use of the latest `master` works:

```
$ bundle
Using kramdown 1.10.0
Using mixlib-cli 1.5.0
Using mixlib-config 2.2.1
Using bundler 1.11.2
Using mdl 0.2.1 from git://github.com/mivok/markdownlint.git (at master@e75d366)
Bundle complete! 1 Gemfile dependency, 5 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ bundle exec mdl --tags ~line_length README.md
# works
```

Would you be willing to release a new version of the gem anytime soon? Thanks!

**Comment by mivok** [comment]
I've just released v0.3.0 which should have the fixes you want.
