### ISSUE TITLE
Carriage Return will crash mdl

### ISSUE THREAD

**Issue by zdw** [markdownlint/markdownlint#190]
A file like this with a carriage return (shown as `<CR>` or `^M` in most unix editors) in it will crash mdl.  An example file:

```
^M[foo](http://foo)
```

As the github editor eats this chracter, a binary copy can be obtained with:

```shell
echo DVtmb29dKGh0dHA6Ly9mb28pCg== | base64 -D > foo.md
```

The error:

```shell
$ mdl foo.md 
/opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl/doc.rb:271:in `extract_text': undefined method `sub' for nil:NilClass (NoMethodError)
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl/rules.rb:313:in `block (3 levels) in load'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl/rules.rb:311:in `each'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl/rules.rb:311:in `block (2 levels) in load'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl.rb:84:in `block (2 levels) in run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl.rb:82:in `each'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl.rb:82:in `block in run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl.rb:72:in `each'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/lib/mdl.rb:72:in `run'
	from /opt/local/lib/ruby2.3/gems/2.3.0/gems/mdl-0.4.0/bin/mdl:10:in `<top (required)>'
	from /opt/local/bin/mdl:22:in `load'
	from /opt/local/bin/mdl:22:in `<main>'
```

**Comment by jamesquilty** [comment]
Duplicate of #237 which has a related Pull Request.

It took me some time to find this bug when searching on the error message. May I suggest that the bug title be updated to read "Carriage Return will crash mdl with 'nil:NilClass (NoMethodError)' message", please.

**Comment by jamesquilty** [comment]
@zdw This was resolved for me in version 0.8.0 by #237. Are you still affected by this crash?

**Comment by jaymzh** [comment]
This was fixed long ago, closing.
