### ISSUE TITLE
MD039: undefined method `type' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by alexxa** [markdownlint/markdownlint#226]
```
/home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl/rules.rb:625:in `block (3 levels) in load': undefined method `type' for nil:NilClass (NoMethodError)
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl/rules.rb:624:in `select'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl/rules.rb:624:in `block (2 levels) in load'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl.rb:86:in `block (2 levels) in run'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl.rb:84:in `each'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl.rb:84:in `block in run'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl.rb:74:in `each'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/lib/mdl.rb:74:in `run'
	from /home/igulina/.gem/ruby/gems/mdl-0.4.0/bin/mdl:10:in `<top (required)>'
	from /home/igulina/bin/mdl:23:in `load'
	from /home/igulina/bin/mdl:23:in `<main>'
```
Markdown file I'm parsing: https://github.com/kubernetes/website/blob/master/content/en/blog/_posts/2017-07-00-Happy-Second-Birthday-Kubernetes.md

**Comment by copperwalls** [comment]
Same error on _mdl-0.5.0_ 🤔

**Comment by copperwalls** [comment]
@alexxa Looks like line 154 is causing `mdl` to crash.

So something like this will trigger it:

```
# I’m A Test File

The following line will crash `mdl`:

[](https://example.com)
```

I think the simplest way to avoid the crash is to add a check similar to the one used in PR #222 🤔

**Comment by copperwalls** [comment]
@alexxa Just opened PR #230. See if it works for you.

**Comment by jaymzh** [comment]
This was fixed a while ago.
