### ISSUE TITLE
"undefined method `params' for nil:NilClass" when defining custom rule

### ISSUE THREAD

**Issue by apjanke** [markdownlint/markdownlint#244]
Hi, markdownlint folks,

I'm having trouble defining a custom rule.

In my linter definition file, I've created a new rule with a simple definition. But when I run it, I get an "undefined method params" error.

```
$ mdl _pages --style _linter/markdown-linter-style.rb
Traceback (most recent call last):
	7: from /Users/janke/bin/mdl:23:in `<main>'
	6: from /Users/janke/bin/mdl:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/bin/mdl:10:in `<top (required)>'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl.rb:26:in `run'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl/style.rb:51:in `load'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl/style.rb:51:in `instance_eval'
	1: from _linter/markdown-linter-style.rb:56:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl/style.rb:30:in `rule': undefined method `params' for nil:NilClass (NoMethodError)
```

This happens even when I just copy and paste the example custom rule from https://github.com/markdownlint/markdownlint/blob/a9e80fcf3989d73b654b00bb2225a00be53983e8/docs/creating_rules.md#creating-rules.

Any idea what's going on here?

I'm using markdownlint 0.5.0.

Reproduction example:

[repro-mdl-no-such-method.zip](https://github.com/markdownlint/markdownlint/files/2697286/repro-mdl-no-such-method.zip)

```
$ make lint
mdl *.md --style style.rb
Traceback (most recent call last):
	7: from /Users/janke/bin/mdl:23:in `<main>'
	6: from /Users/janke/bin/mdl:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/bin/mdl:10:in `<top (required)>'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl.rb:26:in `run'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl/style.rb:51:in `load'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl/style.rb:51:in `instance_eval'
	1: from style.rb:1:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/mdl-0.5.0/lib/mdl/style.rb:30:in `rule': undefined method `params' for nil:NilClass (NoMethodError)
make: *** [lint] Error 1
```

**Comment by apjanke** [comment]
Nevermind. The problem was that I had put the custom rule definition in the style definition file, instead of a separate rules definitions file, so it was calling a different `rule` function. Maybe the "Creating Rules" document should mention where they go.
