### ISSUE TITLE
`update': no implicit conversion of Symbol into Hash (TypeError)

### ISSUE THREAD

**Issue by Bengt** [markdownlint/markdownlint#401]
My `.mdlrc`:

```rc
style "#{File.dirname(__FILE__)}/.mdlrc-style.rb"
```

My `.mdlrc-style.rb`:

```ruby
all
rule 'MD007', :indent => 4
rule 'MD009', :br_spaces => 2
rule 'MD013', :line_length => 99
exclude_rule 'MD019'
rule 'MD030', :ul_single => 3, :ul_multi => 3, :ol_single => 2, :ol_multi => 2
rule 'MD046', :fenced
```

When I try to run markdownlint, I get this error:

```bash
$ mdl README.md
/usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/lib/mdl/ruleset.rb:31:in `update': no implicit conversion of Symbol into Hash (TypeError)
	from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/lib/mdl/ruleset.rb:31:in `params'
	from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/lib/mdl/style.rb:38:in `rule'
	from /builds/iml/vr/vr.backend/.mdlrc-style.rb:7:in `load'
	from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/lib/mdl/style.rb:73:in `instance_eval'
	from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/lib/mdl/style.rb:73:in `load'
	from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/lib/mdl.rb:23:in `run'
	from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.11.0/bin/mdl:10:in `<top (required)>'
	from /usr/bin/mdl:23:in `load'
	from /usr/bin/mdl:23:in `<main>'
```

**Comment by Bengt** [comment]
Whoops, this was my fault. This fixes it:

```ruby
rule 'MD046', :style => :fenced
```
