### ISSUE TITLE
NoMethodError when linting

### ISSUE THREAD

**Issue by RadoRado** [markdownlint/markdownlint#93]
Here is the error i got:

```
/var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/doc.rb:222:in `block (2 levels) in matching_text_element_lines': undefined method `+' for nil:NilClass (NoMethodError)
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/doc.rb:221:in `each'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/doc.rb:221:in `each_with_index'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/doc.rb:221:in `block in matching_text_element_lines'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/doc.rb:218:in `each'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/doc.rb:218:in `matching_text_element_lines'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl/rules.rb:461:in `block (2 levels) in load'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl.rb:71:in `call'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl.rb:71:in `block (2 levels) in run'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl.rb:69:in `each'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl.rb:69:in `block in run'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl.rb:59:in `each'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/lib/mdl.rb:59:in `run'
    from /var/lib/gems/2.1.0/gems/mdl-0.2.1/bin/mdl:10:in `<top (required)>'
    from /usr/local/bin/mdl:23:in `load'
    from /usr/local/bin/mdl:23:in `<main>'
```

Here is the markdown I am trying to lint:

``` markdown
* [Body language, the power is in the palm of your hands | Allan Pease](https://www.youtube.com/watch?v=ZZZ7k8cMA-4)
```

**Comment by mivok** [comment]
This appears to have two causes:
1. A link of the form `[something | something](http://www.example.com)` is parsed by kramdown as a table, and not as a link (but only at a block boundary, putting the same link in the middle of a paragraph is fine).
2. Text elements inside a table don't have line number information associated with them. It's this lack of line number information that causes the crash.

Some possible fixes:
- Changing the table format is slated for the 2.0.0 version of kramdown - https://github.com/gettalong/kramdown/issues/151, although it's possible to disable table parsing just for markdownlint, and I may do this.
- mdl shouldn't crash with bad input regardless, the matching_text_element_lines function should be changed to just not match if it can't find line number information.
- Text inside tables should have line number information - this will require a bug opening with the kramdown project.
