### ISSUE TITLE
MD034 crashes for link description with pipe char "|"

### ISSUE THREAD

**Issue by akoeplinger** [markdownlint/markdownlint#97]
This text in a markdown doc (note the pipe char in the link description):

```
See [|here](http://www.example.com) for more info.
```

results in a crash:

```
[...]
Processing rule MD034
/home/alexander/dev/markdownlint/lib/mdl/doc.rb:222:in `block (2 levels) in matching_text_element_lines': undefined method `+' for nil:NilClass (NoMethodError)
    from /home/alexander/dev/markdownlint/lib/mdl/doc.rb:221:in `each'
    from /home/alexander/dev/markdownlint/lib/mdl/doc.rb:221:in `each_with_index'
    from /home/alexander/dev/markdownlint/lib/mdl/doc.rb:221:in `block in matching_text_element_lines'
    from /home/alexander/dev/markdownlint/lib/mdl/doc.rb:218:in `each'
    from /home/alexander/dev/markdownlint/lib/mdl/doc.rb:218:in `matching_text_element_lines'
    from /home/alexander/dev/markdownlint/lib/mdl/rules.rb:461:in `block (2 levels) in load'
    from /home/alexander/dev/markdownlint/lib/mdl.rb:71:in `call'
    from /home/alexander/dev/markdownlint/lib/mdl.rb:71:in `block (2 levels) in run'
    from /home/alexander/dev/markdownlint/lib/mdl.rb:69:in `each'
    from /home/alexander/dev/markdownlint/lib/mdl.rb:69:in `block in run'
    from /home/alexander/dev/markdownlint/lib/mdl.rb:59:in `each'
    from /home/alexander/dev/markdownlint/lib/mdl.rb:59:in `run'
    from /home/alexander/dev/markdownlint/bin/mdl:10:in `<top (required)>'
    from /home/alexander/.rvm/gems/ruby-2.1.2/bin/mdl:23:in `load'
    from /home/alexander/.rvm/gems/ruby-2.1.2/bin/mdl:23:in `<main>'
    from /home/alexander/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /home/alexander/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>
```

This seems like a weird edge case but I thought I should report it nonetheless :)

**Comment by akoeplinger** [comment]
Sorry, should've looked through the issues list first, looks like a dupe of https://github.com/mivok/markdownlint/issues/93.
